title: Sopel
tagline: The Python IRC Bot
repo: https://github.com/sopel-irc/sopel
docs: https://sopel.chat/docs/

markdown: redcarpet
highlighter: rouge
redcarpet:
    extensions: [tables]

exclude: ['LICENSE', 'README.md', 'Gemfile', 'Gemfile.lock', 'upload.sh']

collections:
  tutorials:
    output: true
  usage:
    output: true

defaults:
  - scope:
      path: "_tutorials"
    values:
      layout: article
      permalink: /tutorials/:name/
  - scope:
      path: "_usage"
    values:
      layout: article
      permalink: /usage/:name/
  - scope:
      path: "_*/index.*"
    values:
      is_index: true
