name: Sopel
tagline: The Python IRC Bot
subtitle: A project of Nerdfighteria Network
repo: https://github.com/sopel-irc/sopel

markdown: redcarpet
highlighter: pygments
redcarpet:
    extensions: [tables]
